- hosts: dnac_servers
  gather_facts: no
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"   
 
  tasks:
    - name: Create CLI Credential
      cisco.dnac.cli_credential:
        <<: *dnac_conn
        state: present
        comments: "created by ansible v2"
        credentialType: "GLOBAL"
        description: "2nd CLI Credential Created By Ansible v2"
        enablePassword: "C1sc0dna!"
        password: "C1sc0dna!"
        username: "netadmin1"

    - name: Create SNMPv2 Read Credential
      cisco.dnac.snmpv2_read_community_credential:
        <<: *dnac_conn
        state: present
        comments: "SNMPv2 Read by Ansible"
        credentialType: "GLOBAL"
        description: "SNMPv2 Read by Ansible"
        readCommunity: "public"

    - name: Create SNMPv2 Write Credential
      cisco.dnac.snmpv2_write_community_credential:
        <<: *dnac_conn
        state: present
        comments: "SNMPv2 Write by Ansible"
        credentialType: "GLOBAL"
        description: "SNMPv2 Write by Ansible"
        writeCommunity: "private"

