- hosts: dnac_servers
  gather_facts: no
  vars:
    dnac_conn: &dnac_conn
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"   
 
  tasks:
    - name: Get Credentials
      cisco.dnac.global_credential_info:
        <<: *dnac_conn
        credentialSubType: "SNMPV2_READ_COMMUNITY"
      register: result

    - name: Work with results
      debug:
        msg:
          - "Results {{result.dnac_response}}"                  